# Generated by Django 3.0.6 on 2020-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('policy_number', models.CharField(max_length=128)),
                ('name_of_insured', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('Motor', 'MOTOR'), ('Health', 'HEALTH'), ('Travel', 'TRAVEL')], max_length=16)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('amount_assured', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
