# Generated by Django 3.0.6 on 2020-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicies',
            name='id',
        ),
        migrations.AlterField(
            model_name='insurancepolicies',
            name='policy_number',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
